# Generated by Django 5.1 on 2024-08-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="myshop_cate_name_35e830_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=150)),
                ("description", models.TextField(max_length=250)),
                ("image", models.ImageField(blank=True, upload_to="product/%y/%m/%d")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="myshop.category",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["id", "slug"], name="myshop_prod_id_2e6696_idx"
                    ),
                    models.Index(fields=["name"], name="myshop_prod_name_021388_idx"),
                    models.Index(
                        fields=["-created"], name="myshop_prod_created_dff7f8_idx"
                    ),
                ],
            },
        ),
    ]
