# Generated by Django 5.1 on 2024-09-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="products/%y/%m/%d"),
        ),
    ]
